First draft of wrapper Makefile
This fails with:

g++ -O3 -fomit-frame-pointer -ffast-math -Wall -fsigned-char -fno-exceptions -fno-rtti -I. -Ishared -Iengine -Igame -Ienet/include -I/usr/X11R6/include `sdl-config --cflags`   -c -o engine/movie.o engine/movie.cpp
engine/movie.cpp:11:23: fatal error: SDL_mixer.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'engine/movie.o' failed
make[1]: *** [engine/movie.o] Error 1

So I am missing a Ubuntu package.